### ISSUE TITLE
[DatasetDownload] File check failed, true_length:167, real_length: 525128288

### ISSUE THREAD

**Issue by klboke** [zilliztech/vectordb-benchmark#21]
Hello, I encountered an exception while testing. The script I executed is as follows：
```shell
./benchmark.sh -d sift-128-euclidean -e milvus -c 1 -c milvus.infra.svc.cluster.local
```

The exception is as follows:
```python
------------------------------------------------- Recall task started! -------------------------------------------------
[check_file_exist] File not exist:/Users/kl/githubnamespace/vectordb-benchmark/datasets/dataset_files/sift-128-euclidean.hdf5
[DatasetDownload] File has been downloaded:/Users/kl/githubnamespace/vectordb-benchmark/datasets/dataset_files/sift-128-euclidean.hdf5
[DatasetDownload] File check failed, true_length:167, real_length: 525128288
Traceback (most recent call last):

  File "/Users/kl/githubnamespace/vectordb-benchmark/./main.py", line 64, in <module>
    app()

  File "/Users/kl/githubnamespace/vectordb-benchmark/./main.py", line 55, in recall
    c.start_recall(dataset_name=dataset_name, prepare=prepare)

  File "/Users/kl/githubnamespace/vectordb-benchmark/client/__init__.py", line 26, in start_recall
    rb.get_dataset_content()

  File "/Users/kl/githubnamespace/vectordb-benchmark/datasets/reader.py", line 33, in get_dataset_content
    DatasetDownload(self.config).download()

  File "/Users/kl/githubnamespace/vectordb-benchmark/datasets/dataset_download.py", line 21, in download
    raise Exception("[DatasetDownload] File check failed:{}".format(self.config.path))

Exception: [DatasetDownload] File check failed:/Users/kl/githubnamespace/vectordb-benchmark/datasets/dataset_files/sift-128-euclidean.hdf5

```

It seems that there is an issue with the validation of the dataset. Can you help me identify the root cause?

**Comment by filip-halt** [comment]
Its  a mac issue I believe. Best route is to go into https://github.com/zilliztech/vectordb-benchmark/blob/main/datasets/dataset_download.py
and bypass check_file_length() by immediately having the function return True.

**Comment by wangting0128** [comment]
@klboke This problem has been fixed, please try again.😊
